- name: Demo on variables
  hosts: localhost
  vars_files:
    - sample-vars.yml
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "URL - {{ URL }}, URL1 - {{ URL1 }}"  # same like shell tou ate accessing variable with prefix $, here variable will be under {{ }}
                                # if the value starts with variable, then it requires quotes and we can use any single or double quotes.
                                # Unlike shell, here in ansible single or double quotes does not have any difference
      vars:
        URL: tasks.example.com
  roles:
    - sample


# Variables precedence
# 1. CLi -e variable
# 2. tasks
# 3. roles vars
# 4. vars_files
# 5. vars
# n. roles defaults

# Variable types
# 1. simple variable
# 2. List
# 3. Dictionary / Map

- name: Variable type demo
  hosts: localhost
  vars:
    CLASS: devops
    timings:
      - 6am
      - 7am
    trainers:
      6am: John
      7am: Peter
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "{{ CLASS }} - {{ timings[0] }}, trainer - {{ trainers[6am] }}"

